import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";

import { Inter } from "next/font/google";
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter-sans",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

import { type Metadata } from "next";
export const metadata: Metadata = {
  title: "DataWow Test",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans`}>
        {children}
        <Toaster richColors theme="light" />
      </body>
    </html>
  );
}
