version: "3.8"

networks:
  app_network:
    name: app_network 
    driver: bridge

services:
  datawowtest_db:
    container_name: datawowtest_db
    platform: linux/x86_64
    image: postgres:16-alpine
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - ${INTERNET_DB_PORT:-5432}:5432
    networks:
      - app_network 
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    restart: unless-stopped

