version: '3.8'

networks:
  app_network:
    name: app_network 
    driver: bridge

services:
  datawowtest_web:
    container_name: datawowtest_web
    image: iamta/datawowtest-web:latest
    env_file:
      - .env.web
    ports:
      - ${INTERNET_WEB_PORT:-8000}:3000
    working_dir: /app
    entrypoint: [ 'node', 'server.js' ]
    restart: unless-stopped
    networks:
      - app_network