version: '3.8'

services:
  portainer_manager:
    container_name: portainer_manager 
    image: 'portainer/portainer:latest'
    restart: unless-stopped
    ports:
      - '9000:9000' 

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data