portainer.up:
	docker-compose -f docker-compose.portainer.yml up -d

portainer.down:
	docker-compose -f docker-compose.portainer.yml down

glances.up:
	docker-compose -f docker-compose.glances.yml up -d

glances.down:
	docker-compose -f docker-compose.glances.yml down