name: pipelines

on:
  push:
    branches: [ "main" ]

jobs:
  build-docker-image:
    name: BuildDockerImage
    runs-on: ubuntu-20.04
    steps:
      - name: Build And Push Image to Docker registry
        uses: actions/checkout@v3
      - run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          
          docker build backend --file backend/Dockerfile.backend --tag iamta/datawowtest-api:latest
          docker push iamta/datawowtest-api:latest

          docker build frontend --file frontend/Dockerfile.frontend --tag iamta/datawowtest-web:latest
          docker push iamta/datawowtest-web:latest